### PR TITLE
Updates and adds missing documents

### PR DESCRIPTION
**Pull request by ptejada**
## Contribution type

Documentation update

## Description of the change

Updates links in the documentation, wording and adds missing documents.

### CODE REVIEW

**Comment by corpsee** [comment]
@ptejada Thank you for the awesome work! Could you move your branch ahead `release-1.0` instead of `master` please?

**Comment by ptejada** [comment]
I am not sure what i need to do here.

From Mobile

**Comment by corpsee** [comment]
It doesn't matter. I merged your changes manually. Thanks!

**Comment by ptejada** [comment]
Thank you. I am curious why you can't just merge the PR? When creating the PR it says whether it can be merged without any conflicts or not and there weren't any conflicts.

**Comment by corpsee** [comment]
Because I should first merge your branch into `release-1.0` and next `release-1.0` into `master`.

**Comment by corpsee** [comment]
I had little time yesterday so I did not write a detailed explanation.

Now stable version is `1.0`, which is located in the `release-1.0` branch. And `master` branch is the future version `1.1`. And the changes should merge consistently into all branches starting from the smaller version to the larger version.

For example, if we have branches: `master` (future `2.0` release), `release-1.1` (releases `1.1.0, 1.1.1` etc.) and `release 1.0`, and we have a bugfix (feature) that is relevant for release `1.1`, then we need to merge bugfix into a `release-1.1` branch, then `release-1.1` into `master` branch.

See Symfony git log, for example. There you can clearly see how the changes merge into all parallel releases sequentially in one direction.

**Comment by corpsee** [comment]
Released with [1.0.4](https://github.com/php-censor/php-censor/releases/tag/1.0.4).

**Pull request closed without merging**
