### PR TITLE
Added variable for interpolation APP_VERSION (%APP_VERSION%).

### LINKED ISSUE #374: [Feature] Add variable for interpolation APP_VERSION
## Expected behavior

Need to add variable for interpolation _APP_VERSION_ (_%APP_VERSION%_).

### PR DESCRIPTION
**Pull request by corpsee**
## Contribution type

Feature.

## Description of change

Fixed #374. Added variable for interpolation APP_VERSION (%APP_VERSION%).

### CODE REVIEW

**Comment by garas** [comment]
Would `PHP_CENSOR_VERSION` be better name? First thing I think when I see this variable that this is version of tested application.

**Comment by corpsee** [comment]
@garas I understand the problem, this is a fair point. But the variable name starting with `PHP_CENSOR_*` looks like an env variable. I guess we need a third variant of the variable name.

**Comment by corpsee** [comment]
May be smt like 'APP_PHP_CENSOR_VERSION'? :smile:

**Comment by garas** [comment]
I think about something like `CI_VERSION` or `SYSTEM_VERSION`, I would avoid `APP`.

**Comment by corpsee** [comment]
Renamed variable `APP_VERSION` to `SYSTEM_VERSION` (`PHP_CENSOR_SYSTEM_VERSION` for env). @garas Thank you for your help! :+1:

**Pull request merged**
