### PR TITLE
PhpUnit with junit runs more stable

### PR DESCRIPTION
**Pull request by SimonHeimberg**
## Contribution type

bug fix / workaround

## Description of change

PhpUnit Plugin works with result in junit format containing invalid characters.

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
a test case is in preparation

**Comment by corpsee** [comment]
@SimonHeimberg Great work, thank you! I will wait for the test cases.

**Comment by corpsee** [comment]
@SimonHeimberg Any news?

**Comment by prezire** [comment]
Conflicts?

**Comment by corpsee** [comment]
@SimonHeimberg I merged this pull request to the `master` branch manually. If you will write tests create new pull request please. Thank you for your work!

**Pull request closed without merging**
