### PR TITLE
Update docs of interpolation variables names

### PR DESCRIPTION
**Pull request by garas**
Some variables were wrong. Reorder to same order as https://github.com/php-censor/php-censor/blob/eebc68f7c5d9c19f90d4051c0e47deedce9f3f2c/src/Helper/BuildInterpolator.php#L35-L48

### CODE REVIEW

**Comment by corpsee** [comment]
@garas I don’t understand what is wrong and what you want to do. Could you give some more details please?

**Comment by garas** [comment]
Sorry, diff is too noisy after resorting. Diff is a bit less noisy if you select _Rich text diff_.

The invalid variables were these (wrong - good):
- PROJECT_ID - PROJECT 
- BUILD_ID - BUILD
- COMMIT_LINK - COMMIT_URI 
- BUILD_LINK - BUILD_URI 
- PROJECT_LINK - PROJECT_URI 
- BRANCH_LINK - BRANCH_URI

**Comment by corpsee** [comment]
@garas No. Documentation is right. `PROJECT`, `PROJECT_URI` etc. are deprecated and will be deleted in version 2.0. So in the docs only preferred names.

See the code comment with `@deprecated` flag:
```php
/** @deprecated The variables are deprecated and will be deleted in version 2.0. Use the variables '%COMMIT_ID%', '%SHORT_COMMIT_ID%' etc. instead. */
$this->interpolationVars['%COMMIT%']       = $this->interpolationVars['%COMMIT_ID%'];
$this->interpolationVars['%SHORT_COMMIT%'] = $this->interpolationVars['%SHORT_COMMIT_ID%'];
$this->interpolationVars['%COMMIT_EMAIL%'] = $this->interpolationVars['%COMMITTER_EMAIL%'];
$this->interpolationVars['%COMMIT_URI%']   = $this->interpolationVars['%COMMIT_LINK%'];
$this->interpolationVars['%PROJECT%']      = $this->interpolationVars['%PROJECT_ID%'];
$this->interpolationVars['%PROJECT_URI%']  = $this->interpolationVars['%PROJECT_LINK%'];
$this->interpolationVars['%BUILD%']        = $this->interpolationVars['%BUILD_ID%'];
$this->interpolationVars['%BUILD_URI%']    = $this->interpolationVars['%BUILD_LINK%'];
$this->interpolationVars['%BRANCH_URI%']   = $this->interpolationVars['%BRANCH_LINK%'];
```

**Comment by garas** [comment]
Yup...

My PHP Censor was left at f57977b (`bitbucket-fix = 1.0.x`). Before testing I was using 1.1.1.

Then I changed Slack message to include `%BRANCH_LINK%` + `%SHORT_COMMIT_ID%`, but it wasn't interpolated, because they were added in `1.1.0`.

Then I looked at docs here again at GitHub (`master=1.2.x`), compared docs + `BuildInterpolator.php` + my non-interpolated string and somehow the `URI/LINK` mixed in my head...

Maybe docs could include info, which of these variables are only 1.1+. Docs here at GitHub links to `master`, but current stable version is 1.1, and I didn't noticed `bitbucket-fix` got me back to 1.0.x.

**Comment by corpsee** [comment]
@garas Thanks anyway!

**Pull request closed without merging**
