### PR TITLE
Feature: todo languages

### PR DESCRIPTION
**Pull request by caouecs**
## Contribution type

new feature on resources

## Description of change

The script generates a file ( todo_languages.md ) with differences between English version and others languages. It is inspired by the script of [Laravel-lang](https://github.com/caouecs/Laravel-lang).

To generate the file :

    php script/todo.php

### CODE REVIEW

**Comment by corpsee** [comment]
Thanks @caouecs!

1. Could you wrap the script (`TodoGenerator` class) by console command (Something like: `./bin/console php-censor:check-localizations`) and print result to console output instead of file?

2. Could you check strings which equel to english too (Not only missing strings)?

**Comment by caouecs** [comment]
1. No problem
2. I will do an option to see or not equality

**Comment by corpsee** [comment]
OK, thank you!

**Comment by caouecs** [comment]
I did a new pull request ( #174 )

**Pull request closed without merging**
