### PR TITLE
Explain the default value of new options in PHP CS Fixer plugin

### PR DESCRIPTION
**Pull request by StudioMaX**
## Contribution type

Bugfix

## Description of change

- Explain the default value of new options in PHP CS Fixer plugin
- added previously dynamically declared `$allowedWarnings` property
- rename option `report-errors` to `report_errors`

### CODE REVIEW

**Comment by corpsee** [comment]
@StudioMaX Yes, we should. Thank you!

**Comment by StudioMaX** [comment]
Done

**Comment by corpsee** [comment]
@StudioMaX Thanks!

**Comment by corpsee** [comment]
Fixed in #197.

**Pull request merged**
