### PR TITLE
support job priority for projects

### PR DESCRIPTION
**Pull request by SimonHeimberg**
## Contribution type

feature

## Description of change

With the project setting 'build_priority', the project builds can get higher or lower priority, which influences the execution order of waiting builds.

### CODE REVIEW

**Comment by SimonHeimberg** [comment]
The first 2 commits are also in pull request xxx.
Maybe the numbers of the priority should be inverted. Currently it is as for beanstalked (low number => urgent, high number => unhurried).

**Comment by corpsee** [comment]
:+1: All is ok but awaiting issue #359 merging.

**Comment by SimonHeimberg** [comment]
I minimized the commits shared between #359 and this to [1 commit](
585ff2c )

**Comment by corpsee** [comment]
Excellent!

**Comment by corpsee** [comment]
Merged manually (Into `master` branch). Would be released with version `1.2`.

**Pull request closed without merging**
